const page = await figma.getNodeByIdAsync('3:2'); await figma.setCurrentPageAsync(page);
await figma.loadFontAsync({ family:'Caveat', style:'Regular' });
const V = async (id) => await figma.variables.getVariableByIdAsync(id);
const c = figma.createComponent();
c.name = 'CodeBlock';
c.layoutMode = 'VERTICAL';
c.primaryAxisSizingMode = 'AUTO';
c.counterAxisSizingMode = 'FIXED';
c.counterAxisAlignItems = 'MIN';
c.primaryAxisAlignItems = 'MIN';
c.itemSpacing = 0;
for (const k of ['paddingTop','paddingBottom','paddingLeft','paddingRight']) c.setBoundVariable(k, await V('VariableID:1:5'));
for (const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius']) c.setBoundVariable(k, await V('VariableID:1:9'));
c.fills = [figma.variables.setBoundVariableForPaint({ type:'SOLID', color:{ r:0.5, g:0.5, b:0.5 } }, 'color', await V('VariableID:2:5'))];
c.strokes = [figma.variables.setBoundVariableForPaint({ type:'SOLID', color:{ r:0, g:0, b:0 } }, 'color', await V('VariableID:2:13'))];
c.setBoundVariable('strokeWeight', await V('VariableID:1:24'));
c.strokeAlign = 'INSIDE';
const t = figma.createText();
t.fontName = { family:'Caveat', style:'Regular' };
t.characters = '## Issue\nfreq knob jitters above 2 kHz\n\n## Steps\n1. add Oscillator\n2. sweep frequency\n3. listen for the click\n\n## Env\noj-core 0.4.2 · webaudio executor';
t.setBoundVariable('fontSize', await V('VariableID:1:14'));
t.lineHeight = { value:145, unit:'PERCENT' };
t.fills = [figma.variables.setBoundVariableForPaint({ type:'SOLID', color:{ r:0, g:0, b:0 } }, 'color', await V('VariableID:2:9'))];
c.appendChild(t);
c.resize(360, c.height);
t.layoutSizingHorizontal = 'FILL';
t.layoutSizingVertical = 'HUG';
t.textAutoResize = 'HEIGHT';
c.x = 1520; c.y = 1000;
return { ids: [c.id] };