/**
 * Doc-drift guard (D5, M7): `docs/agent-tools.md` must list EVERY tool in
 * {@link TOOL_CATALOGUE}.
 *
 * The doc's tool-surface section is generated from the catalogue
 * ({@link catalogueToMarkdown}); this test is the gate that keeps the checked-in
 * markdown from drifting away from the code — adding a tool without documenting
 * it (or vice-versa) fails CI.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { TOOL_CATALOGUE, catalogueToMarkdown } from '../tools';

const DOC_PATH = resolve(process.cwd(), 'docs/agent-tools.md');

describe('docs/agent-tools.md', () => {
    const doc = readFileSync(DOC_PATH, 'utf8');

    it('lists every TOOL_CATALOGUE entry by name', () => {
        for (const tool of TOOL_CATALOGUE) {
            // The bold `**<name>**` row generated by catalogueToMarkdown must be present.
            expect(doc).toContain(`**${tool.name}**`);
        }
    });

    it('embeds the catalogue-rendered markdown verbatim (no drift)', () => {
        // Every generated `- **name** — description` line must appear in the doc,
        // so the doc body is literally the catalogue, not a hand-edited copy.
        for (const line of catalogueToMarkdown().split('\n')) {
            expect(doc).toContain(line);
        }
    });

    it('points at the code-node ABI doc', () => {
        expect(doc).toContain('code-node-abi.md');
    });
});
