/**
 * oj-tokens build — compiles the DTCG sources in `tokens/` into the two
 * artifacts the runtime consumes:
 *
 *   dist/variables.css        the theme-invariant primitives, on :root
 *   src/generated/themes.ts   the per-theme color registry (typed)
 *
 * Run via the repo root: `bun run tokens`. Output is deterministic (no
 * timestamps), so CI can drift-guard it with `git diff --exit-code`.
 *
 * NOTE: we deliberately use only the `name/kebab` transform for the CSS
 * platform — the full `css` transformGroup would rewrite `16px` -> `1rem`
 * (size/rem), changing values. Tokens must round-trip verbatim.
 */

import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const r = (...p) => join(__dirname, ...p);

/** id -> human name. Order here is the order themes appear in the UI picker. */
const THEMES = [
    { id: 'cream', name: 'Cream' },
    { id: 'cyberpunk', name: 'Cyberpunk' },
    { id: 'midnight', name: 'Midnight Blue' },
];

const CSS_HEADER =
    '/* GENERATED by packages/oj-tokens/build.mjs — DO NOT EDIT.\n' +
    '   Edit the DTCG sources in packages/oj-tokens/tokens/ and run `bun run tokens`. */\n\n';

const TS_HEADER =
    '// GENERATED by packages/oj-tokens/build.mjs — DO NOT EDIT.\n' +
    '// Edit the DTCG sources in packages/oj-tokens/tokens/ and run `bun run tokens`.\n\n';

const dtcgValue = (token) => (token.$value !== undefined ? token.$value : token.value);

// 1) Primitives -> dist/variables.css ----------------------------------------
const cssSD = new StyleDictionary(
    {
        source: [r('tokens/primitive.json')],
        platforms: {
            css: {
                transforms: ['name/kebab'],
                buildPath: r('dist') + '/',
                files: [
                    {
                        destination: 'variables.css',
                        format: 'css/variables',
                        options: { selector: ':root', showFileHeader: false },
                    },
                ],
            },
        },
    },
    { verbosity: 'silent' },
);
await cssSD.buildAllPlatforms();

const cssPath = r('dist/variables.css');
const css = await fs.readFile(cssPath, 'utf8');
await fs.writeFile(cssPath, CSS_HEADER + css.trimStart(), 'utf8');

// 2) Per-theme color sets -> src/generated/themes.ts -------------------------
StyleDictionary.registerFormat({
    name: 'oj/colors-object',
    format: ({ dictionary }) => {
        const colors = {};
        for (const token of dictionary.allTokens) {
            colors[token.path[token.path.length - 1]] = dtcgValue(token);
        }
        return JSON.stringify(colors);
    },
});

const themeColors = {};
for (const t of THEMES) {
    const sd = new StyleDictionary(
        {
            source: [r(`tokens/themes/${t.id}.json`)],
            platforms: {
                js: {
                    transforms: [],
                    buildPath: r('dist/_themes') + '/',
                    files: [{ destination: `${t.id}.json`, format: 'oj/colors-object' }],
                },
            },
        },
        { verbosity: 'silent' },
    );
    await sd.buildAllPlatforms();
    themeColors[t.id] = JSON.parse(await fs.readFile(r(`dist/_themes/${t.id}.json`), 'utf8'));
}

// Drop the intermediate per-theme JSON; themes.ts is the committed artifact.
await fs.rm(r('dist/_themes'), { recursive: true, force: true });

const registry = THEMES.map((t) => ({ id: t.id, name: t.name, colors: themeColors[t.id] }));
const ts =
    TS_HEADER +
    `import type { Theme } from '../types';\n\n` +
    `export const generatedThemes: Theme[] = ${JSON.stringify(registry, null, 4)};\n`;

await fs.mkdir(r('src/generated'), { recursive: true });
await fs.writeFile(r('src/generated/themes.ts'), ts, 'utf8');

console.log(
    `oj-tokens: built dist/variables.css and src/generated/themes.ts (${THEMES.length} themes)`,
);
