import type { GlobalProvider } from '@ladle/react'
import { useEffect } from 'react'
// Token primitives (:root vars) + the runtime theme engine — the same source
// the app uses, so the catalog renders components exactly as they ship.
import '../packages/oj-tokens/dist/variables.css'
import { applyTheme, getThemeById, themes } from '@openjammer/oj-tokens'
// The cross-surface map (code ↔ Ladle ↔ Figma ↔ Claude Design), generated by
// `bun run gen:component-map`. Used here to offer a "View in Figma" link per story.
import componentMap from '../component-map.json'

// A global control to switch the active theme live in the catalog — the Phase 3
// "every component reviewable across all themes" requirement.
export const argTypes = {
    ojTheme: {
        control: { type: 'select' },
        options: themes.map((t) => t.id),
        defaultValue: 'cream',
    },
}

// story-component-segment → { Figma master url, name }. The map stores one story id
// per component; we key by its middle segment (`<ns>--<segment>--<variant>`) so ANY
// story of that component resolves to its Figma node.
const figmaBySegment: Record<string, { url: string; name: string }> = {}
for (const c of componentMap.components) {
    if (!c.ladleStoryId || !c.figmaUrl) continue
    const seg = c.ladleStoryId.split('--')[1]
    if (seg && !figmaBySegment[seg]) figmaBySegment[seg] = { url: c.figmaUrl, name: c.name }
}

export const Provider: GlobalProvider = ({ children, globalState }) => {
    const raw = globalState.control?.ojTheme?.value
    const themeId = typeof raw === 'string' ? raw : 'cream'

    useEffect(() => {
        const theme = getThemeById(themeId) ?? themes[0]
        if (theme) applyTheme(theme)
    }, [themeId])

    const segment = globalState.story?.split('--')[1]
    const figma = segment ? figmaBySegment[segment] : undefined

    return (
        <div
            style={{
                minHeight: '100vh',
                padding: 'var(--space-lg)',
                background: 'var(--bg-canvas)',
                color: 'var(--text-primary)',
                fontFamily: 'var(--font-sketch)',
            }}
        >
            {figma && (
                <a
                    href={figma.url}
                    target="_blank"
                    rel="noreferrer"
                    title={`Open the ${figma.name} master in Figma`}
                    style={{
                        position: 'fixed',
                        top: 'var(--space-sm)',
                        right: 'var(--space-sm)',
                        zIndex: 9999,
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: 'var(--space-xs)',
                        padding: 'var(--space-xs) var(--space-sm)',
                        borderRadius: 'var(--radius-sm)',
                        border: 'var(--border-sketch-width) solid var(--sketch-black)',
                        background: 'var(--bg-node)',
                        color: 'var(--text-primary)',
                        fontFamily: 'var(--font-sketch)',
                        fontSize: 'var(--text-sm)',
                        textDecoration: 'none',
                        boxShadow: 'var(--shadow-node)',
                    }}
                >
                    ◈ View in Figma ↗
                </a>
            )}
            {children}
        </div>
    )
}
