// Design-token primitives (:root CSS vars), generated by `bun run tokens` from
// the DTCG sources in packages/oj-tokens. Imported first so the variables exist
// before any component stylesheet. Theme colors are applied at runtime by App.
import '../packages/oj-tokens/dist/variables.css'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import { AppErrorBoundary } from './components/AppErrorBoundary'
import { applyTheme, getSavedThemeId, getThemeById } from '@openjammer/oj-tokens'
import { installConsoleCapture, installGlobalErrorHandlers } from './utils/log'
import { recoverFromStaleBundle } from './utils/staleBundleGuard'
import './components/AppErrorBoundary.css'
import { installE2EBridge } from './test/e2eBridge'
import { PluginWindowShell } from './components/Plugins/PluginWindowShell'

// Route every console.* line into the DevLog ring (and thereby the AI agent's
// get_logs tool) before anything else logs. Idempotent + StrictMode-safe.
installConsoleCapture()

// Catch uncaught errors + unhandled promise rejections that never reach a React
// error boundary, ALLOWLISTED to the app's own origin so third-party / browser
// extension noise never pollutes the DevLog. Must run before app code so an
// early throw is still captured.
installGlobalErrorHandlers()

// Apply the saved/default theme before React's first paint. `index.html` has a
// static boot shell so the native webview never opens as a blank white rectangle;
// this keeps the first React frame on the same paper/ink tokens instead of
// flashing un-themed CSS custom properties.
const initialTheme = getThemeById(getSavedThemeId())
if (initialTheme) applyTheme(initialTheme)

// Desktop only: if the webview's HTTP cache is serving a stale bundle after an
// in-place update, reload once from a cache-busted URL so the player opens on the
// new version (no manual hard refresh). Fire-and-forget — never blocks first
// paint; a no-op in the browser (which has its own service-worker update path).
void recoverFromStaleBundle()
installE2EBridge()

const pluginWindowLabel = new URLSearchParams(window.location.search).get('plugin-window')
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <AppErrorBoundary>
      {pluginWindowLabel ? <PluginWindowShell label={pluginWindowLabel} /> : <App />}
    </AppErrorBoundary>
  </StrictMode>,
)
